FROM python:3.9-slim

WORKDIR /app

# Копируем requirements.txt файлы из всех директорий
COPY middleware/requirements.txt ./middleware/requirements.txt
COPY workers/python_worker_example/requirements.txt ./workers/python_worker_example/requirements.txt
COPY workers/csharp_worker_example/requirements.txt ./workers/csharp_worker_example/requirements.txt
COPY workers/video_worker_example/requirements.txt ./workers/video_worker_example/requirements.txt
COPY workers/rust_worker_example/requirements.txt ./workers/rust_worker_example/requirements.txt

# Устанавливаем все зависимости
RUN pip install --no-cache-dir \
    -r ./middleware/requirements.txt \
    -r ./workers/python_worker_example/requirements.txt \
    -r ./workers/csharp_worker_example/requirements.txt \
    -r ./workers/video_worker_example/requirements.txt \
    -r ./workers/rust_worker_example/requirements.txt

# Копируем тесты и исходный код
COPY tests/ ./tests/
COPY middleware/ ./middleware/
COPY workers/ ./workers/

# Устанавливаем рабочую директорию для тестов
WORKDIR /app/tests

# Запускаем тесты
CMD ["pytest", "-v"]