version: '3'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cerebrum-net

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks:
      - cerebrum-net

  producer:
    build: ./producer
    ports:
      - "5050:5050"
    volumes:
      - ./files:/files:rw
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: unless-stopped
    networks:
      - cerebrum-net

  python_worker_example:
    build: ./workers/python_worker_example
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 20 && celery -A worker worker --loglevel=info"]
    scale: 1
    networks:
      - cerebrum-net

  video_worker_example:
    build: ./workers/video_worker_example
    volumes:
      - ./files:/files:rw
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 20 && celery -A worker worker --loglevel=info"]
    scale: 1
    networks:
      - cerebrum-net

networks:
  cerebrum-net:
    driver: bridge
